version: "3"
services:
  app:
    container_name: img-host
    restart: always
    build: .
    ports:
      - "80:8080"
    links:
      - mongo
    volumes:
      - ./img_host_uploads:/uploads
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db