version: "3"
services:
  app:
    container_name: img-host
    restart: always
    build: .
    ports:
      - "85:8080"
    volumes:
      - ./img_host_uploads:/uploads
      #environment:
      # provide your credentials here
      #- MONGO_INITDB_ROOT_USERNAME=root
      #- MONGO_INITDB_ROOT_PASSWORD=mypass123
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db